### ISSUE TITLE
test.burn.r script EpiModelHIV-p package

### ISSUE THREAD

**Issue by rachelkunowski** [EpiModel/CombPrev#8]
Is EpiModelHIV-p in line 40 of the test/test.burn.r script supposed to be a package? I have access to the EpiModelHIV-p repository, but does it need to be downloaded and compiled into a package separately for this function? Or can the package be made accessible?

devtools::load_all("~/Dropbox/Dev/EpiModelHIV/EpiModelHIV-p")

**Comment by smjenness** [comment]
This was just a local test script, with a local version of the package. It should not be needed to run the full-scale model code.

**Comment by rachelkunowski** [comment]
Hello, 

Thank you! To confirm, the package EpiModelHIV-p shouldn't be needed to run the test.burn.R script? 

Or is it that the burnin/burnin1/sim.R script is the full-scale model code and we can run it without running the test.burn.R script?

**Comment by smjenness** [comment]
EpiModelHIV-p is needed for the test.burn.R script, but the version linked the renv.lock should suffice. It is not necessary to run the test script to run the full model.

**Comment by rachelkunowski** [comment]
I see, thank you! 

I searched but I don't see an EpiModelHIV-p in the renv.lock file. In the original code it's taken locally from a dropbox:
devtools::load_all("~/Dropbox/Dev/EpiModelHIV/EpiModelHIV-p")

What makes this EpiModelHIV-p package different from the EpiModelHIV package? (I see that EpiModelHIV-p is a private repo)

**Comment by smjenness** [comment]
EpiModelHIV-p is the repository name; EpiModelHIV is the R package that repo contains.
